/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PrimeAutoComplete: typeof import('primevue/autocomplete')['default']
    PrimeButton: typeof import('primevue/button')['default']
    PrimeCheckbox: typeof import('primevue/checkbox')['default']
    PrimeChip: typeof import('primevue/chip')['default']
    PrimeColumn: typeof import('primevue/column')['default']
    PrimeColumnGroup: typeof import('primevue/columngroup')['default']
    PrimeConfirmDialog: typeof import('primevue/confirmdialog')['default']
    PrimeConfirmPopup: typeof import('primevue/confirmpopup')['default']
    PrimeDataTable: typeof import('primevue/datatable')['default']
    PrimeDataView: typeof import('primevue/dataview')['default']
    PrimeDatePicker: typeof import('primevue/datepicker')['default']
    PrimeDialog: typeof import('primevue/dialog')['default']
    PrimeForm: typeof import('@primevue/forms/form')['default']
    PrimeIconField: typeof import('primevue/iconfield')['default']
    PrimeIftaLabel: typeof import('primevue/iftalabel')['default']
    PrimeInputIcon: typeof import('primevue/inputicon')['default']
    PrimeInputNumber: typeof import('primevue/inputnumber')['default']
    PrimeInputText: typeof import('primevue/inputtext')['default']
    PrimeMenubar: typeof import('primevue/menubar')['default']
    PrimeMessage: typeof import('primevue/message')['default']
    PrimeOverlayPanel: typeof import('primevue/overlaypanel')['default']
    PrimePanel: typeof import('primevue/panel')['default']
    PrimePassword: typeof import('primevue/password')['default']
    PrimePopover: typeof import('primevue/popover')['default']
    PrimeRow: typeof import('primevue/row')['default']
    PrimeSelect: typeof import('primevue/select')['default']
    PrimeSelectButton: typeof import('primevue/selectbutton')['default']
    PrimeToast: typeof import('primevue/toast')['default']
    PrimeToolbar: typeof import('primevue/toolbar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
