/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PrimeButton: typeof import('primevue/button')['default']
    PrimeCheckbox: typeof import('primevue/checkbox')['default']
    PrimeChip: typeof import('primevue/chip')['default']
    PrimeColumn: typeof import('primevue/column')['default']
    PrimeColumnGroup: typeof import('primevue/columngroup')['default']
    PrimeConfirmDialog: typeof import('primevue/confirmdialog')['default']
    PrimeConfirmPopup: typeof import('primevue/confirmpopup')['default']
    PrimeDataTable: typeof import('primevue/datatable')['default']
    PrimeDataView: typeof import('primevue/dataview')['default']
    PrimeInputNumber: typeof import('primevue/inputnumber')['default']
    PrimeMenu: typeof import('primevue/menu')['default']
    PrimeOverlayPanel: typeof import('primevue/overlaypanel')['default']
    PrimePanel: typeof import('primevue/panel')['default']
    PrimePassword: typeof import('primevue/password')['default']
    PrimeProgressSpinner: typeof import('primevue/progressspinner')['default']
    PrimeRow: typeof import('primevue/row')['default']
    PrimeSelectButton: typeof import('primevue/selectbutton')['default']
    PrimeToast: typeof import('primevue/toast')['default']
    PrimeToolbar: typeof import('primevue/toolbar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
